spring:

  application:
    name: contactmanager

  mvc:
    view:
      prefix: /views/
      suffix: .jsp

  sql:
    init:
      mode: always
  
  datasource:
    url: jdbc:mysql://localhost:3306/sample
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    hibernate:
      sql: debug
    org:
      hibernate:
      type:
        descripter:
          sql:
          BasicBinder: TRACE

debug: true